#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 16 17:46:58 2019

@author: harineem
"""
'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''
import math
def getDivisorCount(n) :
    cnt = 2
    lt = int(math.sqrt(n))+1
    
    for i in range(2,lt):
        if(n%i==0):
           
            cnt = cnt +2
    return cnt
    

#generate the triangle numbers

i = 1
divcnt =1
x = 1
while divcnt<501 :
    x = int(i*(i+1)/2)

    divcnt = getDivisorCount(x)
    i +=1

print(x)


